// ============================================================================
// GrubbinsPixelScene — the shop set piece in PIXEL art.
//
// The alternative to the hand-built PixiJS `GrubbinsScene`, selected by the
// same Settings → Visuals → "Pixel sprites" flag that swaps the unit roster.
// Same props, same aspect, so `ShopScreen` can pick either without knowing
// which it got.
//
// Three layers, one pixel grid:
//   vault_back    the generated room
//   the sprite    grubbins_s_idle / _react, an 8-frame strip in a 160px cell
//   vault_front   the SAME room image with everything that is not counter or
//                 counter-prop punched out of its alpha, so the counter, the
//                 coin stacks and the brass scale all pass IN FRONT of him
//
// Everything is authored at 320x224 and blitted with smoothing off, so the
// scale is nearest-neighbour at whatever width the shop hands us.
//
// The art is generated by the pipeline's "den treatment" (see
// tools/export_to_game.py) — a 160px cell rather than the roster's 80, because
// he stands alone at the top of a screen instead of sharing a field with seven
// others.
// ============================================================================

import { useEffect, useRef } from "react";

interface Props {
  /** CSS pixel width; height follows the scene's 10:7 aspect. */
  width: number;
  /** Bump to make Grubbins visibly pleased for a beat (a purchase landed). */
  reactNonce?: number;
}

/** Authored size of the room. The whole scene is composed at this scale. */
const ROOM_W = 320;
const ROOM_H = 224;
/** Matches GrubbinsScene.SCENE_ASPECT (10:7) so either can fill the same slot. */
export const PIXEL_SCENE_ASPECT = ROOM_W / ROOM_H;

/** Sprite cell + foot anchor, straight from the pixelizer at --cell-scale 2. */
const CELL = 160;
const ANCHOR_X = 80;
const ANCHOR_Y = 144;
/** Where his feet stand in room coordinates (vault counter edge 167 + 33). */
const FEET_X = ROOM_W / 2;
const FEET_Y = 200;

const FRAMES = 8;
/** 400ms a frame. Faster reads as a walk cadence and strobes on a breath. */
const IDLE_MS = 3200;
const REACT_MS = 1600;

const SRC = {
  back: "/sprites/shop/vault_back.png",
  front: "/sprites/shop/vault_front.png",
  idle: "/sprites/pixel/grubbins_s_idle.png",
  react: "/sprites/pixel/grubbins_s_react.png",
};

function loadImage(src: string): Promise<HTMLImageElement> {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.onload = () => resolve(img);
    img.onerror = () => reject(new Error(`failed to load ${src}`));
    img.src = src;
  });
}

export function GrubbinsPixelScene({ width, reactNonce = 0 }: Props) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const reactAtRef = useRef(-Infinity);
  const lastNonceRef = useRef(reactNonce);

  // A nonce bump marks "pleased" time without re-running the load effect.
  if (reactNonce !== lastNonceRef.current) {
    lastNonceRef.current = reactNonce;
    reactAtRef.current = performance.now();
  }

  const height = Math.round(width / PIXEL_SCENE_ASPECT);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    let raf = 0;
    let disposed = false;

    Promise.all([
      loadImage(SRC.back), loadImage(SRC.front),
      loadImage(SRC.idle), loadImage(SRC.react),
    ])
      .then(([back, front, idle, react]) => {
        if (disposed) return;
        const ctx = canvas.getContext("2d");
        if (!ctx) return;

        const draw = () => {
          const now = performance.now();
          const since = now - reactAtRef.current;
          const reacting = since >= 0 && since < REACT_MS;
          const strip = reacting ? react : idle;
          // One-shot while reacting, looping otherwise.
          const t = reacting ? since / REACT_MS : (now % IDLE_MS) / IDLE_MS;
          const frame = Math.min(FRAMES - 1, Math.floor(t * FRAMES));

          const k = canvas.width / ROOM_W;       // device px per authored px
          ctx.imageSmoothingEnabled = false;
          ctx.clearRect(0, 0, canvas.width, canvas.height);
          ctx.drawImage(back, 0, 0, canvas.width, canvas.height);
          ctx.drawImage(
            strip,
            frame * CELL, 0, CELL, CELL,
            (FEET_X - ANCHOR_X) * k, (FEET_Y - ANCHOR_Y) * k, CELL * k, CELL * k
          );
          ctx.drawImage(front, 0, 0, canvas.width, canvas.height);
          raf = requestAnimationFrame(draw);
        };
        draw();
      })
      .catch((e) => {
        // Missing art must not take the shop down — the styled empty canvas
        // stays, exactly as the Pixi scene does when WebGL is unavailable.
        console.error("GrubbinsPixelScene: art failed to load", e);
      });

    return () => {
      disposed = true;
      cancelAnimationFrame(raf);
    };
  }, [width, height]);

  // ⚠ Backing store at DEVICE pixels, CSS size separate. A canvas left at its
  // CSS size is resampled by a fractional DPR, which is fatal for pixel art —
  // the same fix BattleScreen needed.
  const dpr = Math.min(window.devicePixelRatio || 1, 2);

  return (
    <canvas
      ref={canvasRef}
      width={Math.round(width * dpr)}
      height={Math.round(height * dpr)}
      style={{ width, height, display: "block", imageRendering: "pixelated" }}
      aria-label="Grubbins the goblin pawnbroker, behind the counter of his vault shop"
      role="img"
    />
  );
}
